/* Generated by tools/generate_states.py. Do not edit manually. */
#ifndef GENERATED_RUNTIME_STRESS_STATE_HOOKS_H
#define GENERATED_RUNTIME_STRESS_STATE_HOOKS_H

#include "runtime_stress_state.h"

int OnClockTick(KekHookContext* context);
int OnClockPhase(KekHookContext* context);
int OnAgentMoved(KekHookContext* context);
int OnAgentReadOnlyProbeA(KekHookContext* context);
int OnAgentReadOnlyProbeB(KekHookContext* context);
int OnAgentReadOnlyProbeC(KekHookContext* context);
int OnAgentReadOnlyProbeD(KekHookContext* context);
int OnAgentEnergy(KekHookContext* context);
int OnAgentActive(KekHookContext* context);
int OnAgentCreated(KekHookContext* context);
int OnAgentDeleted(KekHookContext* context);
int OnPacketSeq(KekHookContext* context);
int OnPacketPayload(KekHookContext* context);
int OnPacketCreated(KekHookContext* context);
int OnPacketDeleted(KekHookContext* context);
int OnControlMode(KekHookContext* context);
int OnControlLabel(KekHookContext* context);
int OnTelemetryChanged(KekHookContext* context);
int OnAuditChanged(KekHookContext* context);
int OnStandardInput(KekHookContext* context);
int OnFastTimer(KekHookContext* context);
int OnSlowTimer(KekHookContext* context);

#endif /* GENERATED_RUNTIME_STRESS_STATE_HOOKS_H */
