/* Generated by tools/generate_states.py. Do not edit manually. */
#ifndef $guard
#define $guard

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#include "runtime/state_storage.h"
#include "runtime/hook.h"

typedef struct KekString {
    const char* data;
    size_t len;
} KekString;

KekString kek_string_from_cstr(const char* text);
size_t kek_string_len(const KekString* text);

$state_type_enum

$state_declarations

$aggregate_declarations

extern const KekStateDescriptor KekGeneratedStateDescriptors[KEK_STATE_TYPE_COUNT];
const KekStateDescriptor* kek_generated_state_descriptor(size_t type_id);
int kek_generated_state_store_add_defaults(KekStateStore* store,
                                           size_t slot_ids[KEK_STATE_TYPE_COUNT]);

#define KEK_GENERATED_HOOK_COUNT $hook_count
$hook_declarations
extern const KekHookDescriptor* KekGeneratedHookDescriptors;

#endif /* $guard */
