/* Generated by tools/generate_states.py. Do not edit manually. */
#include <string.h>
#include "$header_name"

KekString kek_string_from_cstr(const char* text) {
    KekString value;
    value.data = text;
    value.len = text ? strlen(text) : 0;
    return value;
}

size_t kek_string_len(const KekString* text) {
    return text ? text->len : 0;
}

$state_definitions

const KekStateDescriptor KekGeneratedStateDescriptors[KEK_STATE_TYPE_COUNT] = {
$descriptor_entries
};

const KekStateDescriptor* kek_generated_state_descriptor(size_t type_id) {
    if (type_id >= KEK_STATE_TYPE_COUNT) {
        return 0;
    }
    return &KekGeneratedStateDescriptors[type_id];
}

$instance_definitions

int kek_generated_state_store_add_defaults(KekStateStore* store,
                                           size_t slot_ids[KEK_STATE_TYPE_COUNT]) {
    if (store == 0 || slot_ids == 0) {
        return 0;
    }
    for (size_t i = 0; i < KEK_STATE_TYPE_COUNT; i++) {
        slot_ids[i] = KEK_STATE_INVALID_ID;
    }
    for (size_t i = 0; i < KEK_STATE_TYPE_COUNT; i++) {
        slot_ids[i] = kek_state_store_add(store, &KekGeneratedStateDescriptors[i], 0);
        if (slot_ids[i] == KEK_STATE_INVALID_ID) {
            return 0;
        }
    }
    return 1;
}

$hook_dependency_arrays

$hook_descriptor_table
