/* Generated by tools/generate_states.py. Do not edit manually. */
#ifndef GENERATED_GAME_STATE_HOOKS_H
#define GENERATED_GAME_STATE_HOOKS_H

#include "game_state.h"

int OnFrameClock(KekHookContext* context);
int MoveGruntEnemy(KekHookContext* context);
int MoveRunnerEnemy(KekHookContext* context);
int MoveTankEnemy(KekHookContext* context);
int MoveBossEnemy(KekHookContext* context);
int OnPlayerHealthChanged(KekHookContext* context);
int OnWaveChanged(KekHookContext* context);
int OnScoreChanged(KekHookContext* context);

#endif /* GENERATED_GAME_STATE_HOOKS_H */
