from dataclasses import dataclass
from pathlib import Path

from .model import Enum, Hook, Instance, State
from .naming import c_identifier_from_type, generated_guard
from .parser import parse_source
from .render import emit_graph, emit_header, emit_source


@dataclass
class GeneratedFiles:
    header: str
    source: str
    graph: str


def render_all(states: list[State], hooks: list[Hook], name: str) -> GeneratedFiles:
    return GeneratedFiles(
        emit_header(states, hooks, [], name),
        emit_source(states, hooks, [], name),
        emit_graph(states, hooks, [], name),
    )


def render_all_model(states: list[State], hooks: list[Hook], instances: list[Instance], name: str) -> GeneratedFiles:
    return GeneratedFiles(
        emit_header(states, hooks, instances, name),
        emit_source(states, hooks, instances, name),
        emit_graph(states, hooks, instances, name),
    )


def render_all_schema(
    enums: list[Enum],
    states: list[State],
    hooks: list[Hook],
    instances: list[Instance],
    name: str,
) -> GeneratedFiles:
    return GeneratedFiles(
        emit_header(states, hooks, instances, name, enums),
        emit_source(states, hooks, instances, name, enums),
        emit_graph(states, hooks, instances, name),
    )


def render_hook_api_header(hooks: list[Hook], name: str) -> str:
    guard = generated_guard(f"{name}_hooks")
    lines = [
        "/* Generated by tools/generate_states.py. Do not edit manually. */",
        f"#ifndef {guard}",
        f"#define {guard}",
        "",
        f'#include "{name}.h"',
        "",
    ]
    if hooks:
        lines.extend(f"int {hook.name}(KekHookContext* context);" for hook in hooks)
    lines.extend(["", f"#endif /* {guard} */", ""])
    return "\n".join(lines)


def render_hook_stub(hook: Hook, name: str) -> str:
    return "\n".join(
        [
            "/* Generated hook stub. Edit this file to implement the hook. */",
            f'#include "{name}_hooks.h"',
            "",
            f"int {hook.name}(KekHookContext* context) {{",
            "    (void)context;",
            "    return 1;",
            "}",
            "",
        ]
    )


def write_hook_files(hooks: list[Hook], hooks_dir: str | Path, name: str) -> tuple[Path, list[Path]]:
    output_dir = Path(hooks_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    header_path = output_dir / f"{name}_hooks.h"
    header_path.write_text(render_hook_api_header(hooks, name), encoding="utf-8")

    written: list[Path] = []
    for hook in hooks:
        source_path = output_dir / f"{c_identifier_from_type(hook.name)}.c"
        if source_path.exists():
            continue
        source_path.write_text(render_hook_stub(hook, name), encoding="utf-8")
        written.append(source_path)
    return header_path, written


def write_generated_files(
    source: str,
    out_dir: str | Path,
    name: str,
    hooks_dir: str | Path | None = None,
) -> tuple[Path, Path, Path]:
    enums, states, hooks, instances = parse_source(source)
    generated = render_all_schema(enums, states, hooks, instances, name)

    output_dir = Path(out_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    header_path = output_dir / f"{name}.h"
    source_path = output_dir / f"{name}.c"
    graph_path = output_dir / f"{name}.graph.md"

    header_path.write_text(generated.header, encoding="utf-8")
    source_path.write_text(generated.source, encoding="utf-8")
    graph_path.write_text(generated.graph, encoding="utf-8")
    if hooks_dir is not None:
        write_hook_files(hooks, hooks_dir, name)
    return header_path, source_path, graph_path
