from dataclasses import dataclass
from pathlib import Path

from .model import Enum, Hook, HookAccess, Instance, State
from .naming import c_identifier_from_type, generated_guard
from .parser import parse_source
from .render import c_type, emit_graph, emit_header, emit_source, generated_prefix


@dataclass
class GeneratedFiles:
    header: str
    source: str
    graph: str


def render_all(states: list[State], hooks: list[Hook], name: str) -> GeneratedFiles:
    return GeneratedFiles(
        emit_header(states, hooks, [], name),
        emit_source(states, hooks, [], name),
        emit_graph(states, hooks, [], name),
    )


def render_all_model(states: list[State], hooks: list[Hook], instances: list[Instance], name: str) -> GeneratedFiles:
    return GeneratedFiles(
        emit_header(states, hooks, instances, name),
        emit_source(states, hooks, instances, name),
        emit_graph(states, hooks, instances, name),
    )


def render_all_schema(
    enums: list[Enum],
    states: list[State],
    hooks: list[Hook],
    instances: list[Instance],
    name: str,
) -> GeneratedFiles:
    return GeneratedFiles(
        emit_header(states, hooks, instances, name, enums),
        emit_source(states, hooks, instances, name, enums),
        emit_graph(states, hooks, instances, name),
    )


def render_hook_api_header(
    hooks: list[Hook],
    name: str,
    states: list[State] | None = None,
    instances: list[Instance] | None = None,
) -> str:
    guard = generated_guard(f"{name}_hooks")
    states = states or []
    instances = instances or []
    lines = [
        "/* Generated by tools/generate_states.py. Do not edit manually. */",
        f"#ifndef {guard}",
        f"#define {guard}",
        "",
        f'#include "{name}.h"',
        "",
    ]
    if hooks:
        lines.extend(f"int {hook.name}(KekHookContext* context);" for hook in hooks)
        lines.append("")
        lines.extend(render_strict_hook_api(hooks, name, states, instances))
    lines.extend(["", f"#endif /* {guard} */", ""])
    return "\n".join(lines)


def render_strict_hook_api(hooks: list[Hook], name: str, states: list[State], instances: list[Instance]) -> list[str]:
    prefix = generated_prefix(name)
    slots_type = f"{name[:1].upper()}{name[1:]}StateSlots"
    state_by_name = {state.name: state for state in states}
    instance_by_name = {instance.name: instance for instance in instances}
    lines: list[str] = [
        "/* Strict per-hook helpers. Use these wrappers inside generated hook implementations. */",
    ]
    for hook in hooks:
        hook_snake = c_identifier_from_type(hook.name)
        access_type = f"{hook.name}Access"
        lines.extend(
            [
                f"typedef struct {access_type} {{",
                "    KekHookContext* context;",
                f"    const {slots_type}* slots;",
                f"}} {access_type};",
                "",
                f"static inline {access_type} {hook_snake}_access(KekHookContext* context, const {slots_type}* slots) {{",
                f"    {access_type} access = {{context, slots}};",
                "    return access;",
                "}",
                "",
            ]
        )
        if not hook.accesses:
            lines.append(f"/* {hook.name}: no precise access metadata; use legacy generated helpers deliberately. */")
            lines.append("")
            continue
        if hook.scheduling_opaque:
            lines.append(f"/* {hook.name}: opaque access forces serial scheduling. */")
            lines.append("")
        rendered: set[str] = set()
        rendered_slots: set[str] = set()
        for access in hook.accesses:
            if access.instance_name is not None:
                instance = instance_by_name[access.instance_name]
                state = state_by_name[instance.state_name]
                key = f"{access.mode}:{access.instance_name}"
                if key in rendered:
                    continue
                rendered.add(key)
                emit_slot_id = access.instance_name not in rendered_slots
                rendered_slots.add(access.instance_name)
                lines.extend(render_instance_access_helpers(prefix, hook_snake, access_type, access, state, emit_slot_id))
                continue
            state = state_by_name.get(access.state_name)
            if state is None:
                raise ValueError(f"{hook.name}: cannot emit strict helper for unknown state {access.state_name}")
            key = f"{access.mode}:{access.state_name}:{access.scope}"
            if key in rendered:
                continue
            rendered.add(key)
            lines.extend(render_state_access_helpers(prefix, hook_snake, access_type, access, state))
        lines.append("")
    return lines


def render_instance_access_helpers(prefix: str, hook_snake: str, access_type: str, access: HookAccess, state: State, emit_slot_id: bool) -> list[str]:
    state_snake = c_identifier_from_type(state.name)
    instance = access.instance_name
    lines: list[str] = []
    if emit_slot_id:
        lines.extend(
            [
                f"static inline KekStateHandle {hook_snake}_{instance}_handle(const {access_type}* access) {{",
                f"    return access && access->slots ? access->slots->{instance} : KEK_STATE_INVALID_ID;",
                "}",
                "",
                f"static inline KekStateHandle {hook_snake}_{instance}_slot_id(const {access_type}* access) {{",
                f"    return {hook_snake}_{instance}_handle(access);",
                "}",
                "",
            ]
        )
    if access.mode == "KEK_HOOK_ACCESS_READ":
        lines.extend(
            [
                f"static inline const {state.name}* {hook_snake}_read_{instance}(const {access_type}* access) {{",
                f"    return access ? {prefix}_{state_snake}_instance_const(access->context->state_store, {hook_snake}_{instance}_handle(access)) : 0;",
                "}",
                "",
            ]
        )
    if access.mode == "KEK_HOOK_ACCESS_WRITE":
        lines.extend(
            [
                f"static inline int {hook_snake}_update_{instance}(const {access_type}* access, KekStateUpdateFn update, void* context, uint64_t changed_fields) {{",
                f"    return access ? kek_state_store_update_fields(access->context->state_store, {hook_snake}_{instance}_handle(access), update, context, changed_fields) : 0;",
                "}",
                "",
            ]
        )
        allowed_fields = set(access.fields)
        for field in state.fields:
            if allowed_fields and field.name not in allowed_fields:
                continue
            if field.array_length is not None:
                continue
            if field.type_name == "String":
                lines.extend(
                    [
                        f"static inline int {hook_snake}_set_{instance}_{field.name}(const {access_type}* access, const char* data, size_t len) {{",
                        f"    return access ? {prefix}_{state_snake}_set_{field.name}(access->context->state_store, {hook_snake}_{instance}_handle(access), data, len) : 0;",
                        "}",
                        "",
                    ]
                )
            else:
                lines.extend(
                    [
                        f"static inline int {hook_snake}_set_{instance}_{field.name}(const {access_type}* access, {c_type(field.type_name)} value) {{",
                        f"    return access ? {prefix}_{state_snake}_set_{field.name}(access->context->state_store, {hook_snake}_{instance}_handle(access), value) : 0;",
                        "}",
                        "",
                    ]
                )
    if access.mode == "KEK_HOOK_ACCESS_DELETE":
        lines.extend(
            [
                f"static inline int {hook_snake}_delete_{instance}(const {access_type}* access) {{",
                f"    return access ? {prefix}_{state_snake}_delete(access->context->state_store, {hook_snake}_{instance}_handle(access)) : 0;",
                "}",
                "",
            ]
        )
    if access.mode == "KEK_HOOK_ACCESS_CREATE":
        raise ValueError(f"{hook_snake}: create access cannot target exact instance {instance}")
    return lines


def render_state_access_helpers(prefix: str, hook_snake: str, access_type: str, access: HookAccess, state: State) -> list[str]:
    state_snake = c_identifier_from_type(state.name)
    lines: list[str] = []
    if access.mode == "KEK_HOOK_ACCESS_READ":
        lines.extend(
            [
                f"static inline KekStateHandle {hook_snake}_first_{state_snake}(const {access_type}* access) {{",
                f"    return access ? {prefix}_{state_snake}_first(access->context->state_store) : KEK_STATE_INVALID_ID;",
                "}",
                f"static inline KekStateHandle {hook_snake}_next_{state_snake}(const {access_type}* access, KekStateHandle after_handle) {{",
                f"    return access ? {prefix}_{state_snake}_next(access->context->state_store, after_handle) : KEK_STATE_INVALID_ID;",
                "}",
                f"static inline const {state.name}* {hook_snake}_read_{state_snake}_instance(const {access_type}* access, KekStateHandle handle) {{",
                f"    return access ? {prefix}_{state_snake}_instance_const(access->context->state_store, handle) : 0;",
                "}",
                f"static inline const {state.name}* {hook_snake}_read_{state_snake}_slot(const {access_type}* access, KekStateHandle handle) {{",
                f"    return {hook_snake}_read_{state_snake}_instance(access, handle);",
                "}",
                "",
            ]
        )
    if access.mode == "KEK_HOOK_ACCESS_WRITE":
        lines.extend(
            [
                f"static inline int {hook_snake}_update_{state_snake}_instance(const {access_type}* access, KekStateHandle handle, KekStateUpdateFn update, void* context, uint64_t changed_fields) {{",
                "    return access ? kek_state_store_update_fields(access->context->state_store, handle, update, context, changed_fields) : 0;",
                "}",
                f"static inline int {hook_snake}_update_{state_snake}_slot(const {access_type}* access, KekStateHandle handle, KekStateUpdateFn update, void* context, uint64_t changed_fields) {{",
                f"    return {hook_snake}_update_{state_snake}_instance(access, handle, update, context, changed_fields);",
                "}",
                "",
            ]
        )
    if access.mode == "KEK_HOOK_ACCESS_CREATE":
        lines.extend(
            [
                f"static inline KekStateHandle {hook_snake}_create_{state_snake}(const {access_type}* access) {{",
                f"    return access ? {prefix}_{state_snake}_create(access->context->state_store) : KEK_STATE_INVALID_ID;",
                "}",
                f"static inline KekStateHandle {hook_snake}_create_{state_snake}_with(const {access_type}* access, const {state.name}* initial) {{",
                f"    return access ? {prefix}_{state_snake}_create_with(access->context->state_store, initial) : KEK_STATE_INVALID_ID;",
                "}",
                "",
            ]
        )
    if access.mode == "KEK_HOOK_ACCESS_DELETE":
        lines.extend(
            [
                f"static inline int {hook_snake}_delete_{state_snake}_instance(const {access_type}* access, KekStateHandle handle) {{",
                f"    return access ? {prefix}_{state_snake}_delete(access->context->state_store, handle) : 0;",
                "}",
                f"static inline int {hook_snake}_delete_{state_snake}_slot(const {access_type}* access, KekStateHandle handle) {{",
                f"    return {hook_snake}_delete_{state_snake}_instance(access, handle);",
                "}",
                "",
            ]
        )
    if not lines:
        raise ValueError(f"{hook_snake}: unsupported access mode {access.mode}")
    return lines


def render_hook_stub(hook: Hook, name: str) -> str:
    return "\n".join(
        [
            "/* Generated hook stub. Edit this file to implement the hook. */",
            f'#include "{name}_hooks.h"',
            "",
            f"int {hook.name}(KekHookContext* context) {{",
            "    (void)context;",
            "    return 1;",
            "}",
            "",
        ]
    )


def write_hook_files(
    hooks: list[Hook],
    hooks_dir: str | Path,
    name: str,
    states: list[State] | None = None,
    instances: list[Instance] | None = None,
) -> tuple[Path, list[Path]]:
    output_dir = Path(hooks_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    header_path = output_dir / f"{name}_hooks.h"
    header_path.write_text(
        render_hook_api_header(hooks, name, states, instances),
        encoding="utf-8",
    )

    written: list[Path] = []
    for hook in hooks:
        source_path = output_dir / f"{c_identifier_from_type(hook.name)}.c"
        if source_path.exists():
            continue
        source_path.write_text(render_hook_stub(hook, name), encoding="utf-8")
        written.append(source_path)
    return header_path, written


def write_generated_files(
    source: str,
    out_dir: str | Path,
    name: str,
    hooks_dir: str | Path | None = None,
) -> tuple[Path, Path, Path]:
    enums, states, hooks, instances = parse_source(source)
    generated = render_all_schema(enums, states, hooks, instances, name)

    output_dir = Path(out_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    header_path = output_dir / f"{name}.h"
    source_path = output_dir / f"{name}.c"
    graph_path = output_dir / f"{name}.graph.md"

    header_path.write_text(generated.header, encoding="utf-8")
    source_path.write_text(generated.source, encoding="utf-8")
    graph_path.write_text(generated.graph, encoding="utf-8")
    if hooks_dir is not None:
        write_hook_files(hooks, hooks_dir, name, states, instances)
    return header_path, source_path, graph_path
